Repository Catch-team/Catch_FE, pull requests merged in 2024-04, with the labels that each got.

#8 [Feat] Header Footer 설정 (#7)
  src/App.vue
  src/components/AppHeader.vue
  src/components/AppSideBar.vue
  src/components/views/DashBoard.vue
  src/components/views/PostList.vue
  src/components/views/UserList.vue
  src/router/index.js
Labels: ✨feat

#12 [Feat] CRUD FE 개발 #10
  .env
  src/components/AppSideBar.vue
  src/components/views/CouponCreate.vue
  src/components/views/CouponList.vue
  src/router/index.js
  tailwind.config.js
Labels: ✨feat

#11 [Feat] 관리자 로그인 화면 구현 (#9)
  src/App.vue
  src/components/AppHeader.vue
  src/components/AppSideBar.vue
  src/components/LoginAdmin.vue
  src/components/Login_User.vue
  src/components/views/DashBoard.vue
  src/router/index.js
Labels: ✨feat

#15 사이드바 에러 수정
  src/components/AppSideBar.vue
  src/components/views/CouponList.vue
Labels: ⚙chore

#17 Feature/sim 16
  src/components/AppSideBar.vue
  src/components/views/CouponList.vue
  src/components/views/DashBoard.vue
Labels: ✨feat

#18 [Feat] 계정 생성, 계정리스트 화면 구현 #13
  src/components/AppSideBar.vue
  src/components/views/AdminList.vue
  src/components/views/CouponList.vue
  src/components/views/MarketerCsCreate.vue
  src/router/index.js
Labels: ✨feat

#19 [Feat] DashBoard 페이지 제작 (#16)
  src/components/views/DashBoard.vue
  src/components/views/PostList.vue
Labels: ✨feat

#29 [Feat] 통계 데이터 정보 제공 기능 구현 (#26)
  src/views/ComplaintList.vue
  src/views/DashBoard.vue
Labels: ✨feat

#31 [Feat] 관리자 계정 상세조회, 수정, 비활성화, 활성화
  src/components/AppHeader.vue
  src/components/AppSideBar.vue
  src/components/PaginationComponent.vue
  src/components/modal/AdminDetailModal.vue
  src/components/modal/ModalComponent.vue
  src/router/index.js
  src/views/AdminList.vue
  src/views/LoginAdmin.vue
  src/views/MarketerCsCreate.vue
Labels: ✨feat

#36 push 알람
  .env.production
  .gitignore
  src/App.vue
  src/views/CouponCreate.vue
  src/views/CouponList.vue
  src/views/UserList.vue
Labels: ✨feat

#38 [Feat, Fix] url 수정 및 접근 권한 설정, 권한 없음 페이지 추가
  src/App.vue
  src/assets/403.png
  src/components/AdminFooter.vue
  src/components/AdminHeader.vue
  src/components/UserFooter.vue
  src/components/UserHeader.vue
  src/router/index.js
  src/views/LoginAdmin.vue
  src/views/LoginUser.vue
  src/views/UnauthorizedPage.vue
Labels: ✨feat, ♻refactor

#41 [Feat] User Header, MyProfileSid 추가
  .env.production
  src/components/MyProfileSide.vue
  src/components/UserHeader.vue
  src/views/LoginUser.vue
  src/views/MyPage.vue
Labels: ✨feat

#48 [Feat, Fix] 고객리스트, 관리자 리스트, 상세 모달 수정 및 구현
  src/components/modal/AdminDetailModal.vue
  src/components/modal/UserDetailModal.vue
  src/views/AdminList.vue
  src/views/UserList.vue
Labels: ✨feat, ♻refactor

#50 [Feat] 관리자페이지 문의 글 상세정보 보기 기능 구현 (#47)
  src/App.vue
  src/assets/tailwind.css
  src/components/AppSideBar.vue
  src/components/ComplaintDetailComponent.vue
  src/components/modal/ComplaintDetailModal.vue
  src/main.js
  src/router/index.js
  src/views/ComplaintDetail.vue
  src/views/ComplaintList.vue
  src/views/CouponCreate.vue
  src/views/CouponList.vue
  src/views/CreateComplaint.vue
  src/views/MyComplaintList.vue
  src/views/MyPage.vue
Labels: ✨feat

#52 쿠폰 마무리
  src/components/MyProfileContentsCoupon.vue
  src/components/MyProfileSide.vue
  src/components/MyProfileTop.vue
  src/components/modal/CouponReceiveModal.vue
  src/components/modal/MyCouponListModal.vue
  src/components/modal/SelectUserModal.vue
  src/views/CouponList.vue
  src/views/CouponReceive.vue
Labels: ✨feat

#57 [Fix] 고객 헤더, 관리자 헤더 수정, 쿠폰생성 디자인 수정
  src/components/AdminFooter.vue
  src/components/AdminHeader.vue
  src/components/UserHeader.vue
  src/views/AdminList.vue
  src/views/CouponCreate.vue
  src/views/MarketerCsCreate.vue
Labels: ♻refactor

#58 로그인 차트 수정
  src/views/DashBoard.vue
Labels: ♻refactor

#59 쿠폰 발행 대상 검색 로직 수정
  src/components/modal/SelectUserModal.vue
Labels: ✨feat

#60 [Feat] 이벤트 생성
  src/views/eventCreate.vue
Labels: ✨feat, ♻refactor

#62 [Feat] 이벤트 생성
  src/components/AppSideBar.vue
  src/components/modal/EventDetailModal.vue
  src/router/index.js
  src/views/EventList.vue
Labels: ✨feat

#65 [Fix] [Fix] 관리자 대시보드 페이지 컴포넌트화 (#64)
  package-lock.json
  package.json
  src/components/ComplaintDashBoardComponent.vue
  src/components/EventDashBoardComponent.vue
  src/components/UserDashBoardComponent.vue
  src/views/DashBoard.vue
Labels: ✨feat, ♻refactor

#69 [Feat, Fix] 토큰 만료 됐을때 로직 수정, 1시간 동안 활동이없으면 로그아웃 추가
  src/axios/index.js
  src/components/AdminHeader.vue
  src/components/ComplaintDetailComponent.vue
  src/components/CreateComplaintComponent.vue
  src/components/MyComplaintListComponent.vue
  src/components/MyProfileContentsCoupon.vue
  src/components/MyProfileContentsShop.vue
  src/components/MyProfileTop.vue
  src/components/UserHeader.vue
  src/components/modal/AdminDetailModal.vue
  src/components/modal/ComplaintDetailModal.vue
  src/components/modal/CouponReceiveModal.vue
  src/components/modal/EventDetailModal.vue
  src/components/modal/MyCouponListModal.vue
  src/components/modal/SelectUserModal.vue
  src/components/modal/UserDetailModal.vue
  src/router/index.js
  src/views/AdminList.vue
  src/views/ComplaintList.vue
  src/views/CouponCreate.vue
  src/views/CouponList.vue
  src/views/CouponReceive.vue
  src/views/EventList.vue
  src/views/MarketerCsCreate.vue
  src/views/UserList.vue
  src/views/eventCreate.vue
Labels: ✨feat, ♻refactor

#70 문의글 대시보드 차트 제작
  src/components/ComplaintDashBoardComponent.vue
  src/components/UserDashBoardComponent.vue
  src/views/ComplaintList.vue
Labels: ✨feat, ♻refactor

#71 [feat] 문의글 대시보드 제작 완료
  src/components/ComplaintDashBoardComponent.vue
Labels: ✨feat, ♻refactor
