Repository Catch-team/Catch_FE, pull requests merged in 2024-05, with the labels that each got.

#73 [Feat] 이벤트보기 페이지 추가
  src/components/MyProfileTop.vue
  src/router/index.js
  src/views/EventBanner.vue
  src/views/LoginAdmin.vue
  src/views/LoginUser.vue
  src/views/MyEvent.vue
Labels: ✨feat

#72 [feat] 고객 대시보드 제작
  src/components/ComplaintDashBoardComponent.vue
  src/components/UserDashBoardComponent.vue
Labels: ✨feat, ♻refactor

#75 [Fix] 이벤트가 없으면 이벤트 없다고 뜸
  src/views/MyEvent.vue
Labels: ♻refactor

#74 이벤트 알람 구현
  src/components/MyProfileContentsCoupon.vue
  src/components/modal/CouponDetailModal.vue
  src/components/modal/SelectCouponUserModal.vue
  src/components/modal/SelectEventUserModal.vue
  src/views/CouponCreate.vue
  src/views/CouponList.vue
  src/views/EventList.vue
  src/views/eventCreate.vue
Labels: ✨feat

#80 [fix] 프로젝트 유지보수
  src/components/AppSideBar.vue
  src/components/ComplaintDetailComponent.vue
  src/components/CreateComplaintComponent.vue
  src/components/MyProfileContents.vue
  src/components/MyProfileContentsCoupon.vue
  src/components/MyProfileContentsShop.vue
  src/components/MyProfileTop.vue
  src/components/UserDashBoardComponent.vue
  src/components/modal/MyCouponListModal.vue
  src/components/modal/UserDetailModal.vue
  src/views/LoginUser.vue
  src/views/MarketerCsCreate.vue
  src/views/UserList.vue
Labels: ♻refactor

#84 쿠폰 디자인
  src/assets/coupon_image.png
  src/components/MyProfileContentsCoupon.vue
  src/components/UserHeader.vue
  src/components/modal/NotificationListModal.vue
  src/views/CouponCreate.vue
  src/views/MarketerCsCreate.vue
Labels: ✨feat

#86 firebase 파일 설정
  .gitignore
  public/firebase-messaging-sw.js
  src/components/ComplaintDashBoardComponent.vue
  src/components/modal/EventChartModal.vue
  src/views/EventList.vue
Labels: ⚙chore

#85 상태 수정
  src/components/modal/SelectCouponUserModal.vue
  src/components/modal/SelectEventUserModal.vue
  src/views/CouponList.vue
  src/views/EventList.vue
Labels: ✨feat

#88 미수신 알람
  public/firebase-messaging-sw.js
  src/App.vue
  src/components/UserHeader.vue
  src/components/modal/NotificationListModal.vue
  src/components/modal/SelectCouponUserModal.vue
  src/components/modal/SelectUserModal.vue
  src/views/CouponList.vue
  src/views/LoginUser.vue
Labels: ✨feat

#90 쿠폰 4개 미만
  src/components/MyProfileContentsCoupon.vue
Labels: ✨feat

#91 쿠폰 받기 수정
  src/components/modal/CouponReceiveModal.vue
Labels: ✨feat

#92 쿠폰 이름 길이 수정
  src/components/MyProfileContentsCoupon.vue
  src/components/modal/CouponChartModal.vue
  src/components/modal/MyCouponListModal.vue
  src/components/modal/SelectCouponUserModal.vue
  src/components/modal/SelectEventUserModal.vue
  src/views/CouponCreate.vue
  src/views/eventCreate.vue
Labels: ✨feat

#93 문의글 캠페인 카테고리 추가
  src/views/ComplaintList.vue
  src/views/CouponList.vue
  src/views/EventList.vue
Labels: ✨feat

#94 게시글 문의글로 수정
  src/components/modal/SelectEventUserModal.vue
  src/views/ComplaintList.vue
Labels: ✨feat

#95 쿠폰 수정 상태
  src/components/MyProfileSide.vue
  src/views/CouponList.vue
Labels: ✨feat

#96 쿠폰 중복 수정 메세지
  src/components/modal/CouponReceiveModal.vue
  src/views/EventList.vue
Labels: ✨feat

#97 쿠폰, 캠페인 삭제
  src/components/modal/UserDetailModal.vue
  src/views/CouponList.vue
  src/views/EventList.vue
Labels: ✨feat

#98 체크박스 수정
  src/components/modal/SelectCouponUserModal.vue
  src/views/CouponList.vue
  src/views/EventList.vue
Labels: ✨feat
